version: '3'
services:
  app:
    build: ./Order
    #ports:
    # - "80:80"
    links:
      - "redis"
    expose:
      - "80"
    networks:
      - spring
  redis:
    image: "redis:alpine"
    #hostname: redis
    command: [ "redis-server", "--protected-mode", "no" ]
    ports:
     - "6379:6379"
    networks:
      - spring

  nginx:
    image: nginx:latest
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "app"
    ports:
      - "80:80"
    links:
      - "app"

networks:
  spring:
    external: true