version: '2'
services:
  app:
    build: .
    dockerfile: ./Order/Dockerfile
    ports:
     - "8080:8080"
    links:
      - "db:redis"
  db:
    image: "redis:alpine"
    hostname: redis
    ports:
     - "6379:6379"