version: '2'
services:
  app:
    build: ./Order
    ports:
     - "8080:8080"
    links:
      - "db:redis"
    networks:
      - spring
  db:
    image: "redis:alpine"
    hostname: redis
    ports:
     - "6379:6379"
    networks:
      - spring

networks:
  spring:
    external: true