version: '2'
services:
  app:
    build: ./Order
    ports:
     - "8080:8080"
    links:
      - "redis"
    networks:
      - spring
  redis:
    image: "redis:alpine"
    #hostname: redis
    command: [ "redis-server", "--protected-mode", "no" ]
    ports:
     - "6379:6379"
    networks:
      - spring

networks:
  spring:
    external: true